# Generated by Django 3.0.7 on 2020-09-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200912_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update',
        ),
    ]
