# Generated by Django 3.0.7 on 2020-09-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200912_2334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'id')},
        ),
    ]
