# Generated by Django 3.0.7 on 2020-09-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200913_0158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'id')},
        ),
    ]
