# Generated by Django 3.0.7 on 2020-09-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200914_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
